"""empty message

Revision ID: 0c2c59678b44
Revises: b70de4a28583
Create Date: 2024-04-25 19:40:02.935917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2c59678b44'
down_revision = 'b70de4a28583'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attachment_id_application_fkey', 'attachment', type_='foreignkey')
    op.create_foreign_key(None, 'attachment', 'application', ['id_application'], ['id_application'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.create_foreign_key('attachment_id_application_fkey', 'attachment', 'application', ['id_application'], ['id_application'])
    # ### end Alembic commands ###
