"""empty message

Revision ID: 4f4cdb755fb2
Revises: d2880cca3c27
Create Date: 2024-04-24 00:26:36.261161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4cdb755fb2'
down_revision = 'd2880cca3c27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
