"""empty message

Revision ID: b70de4a28583
Revises: cf05b2859d56
Create Date: 2024-04-25 19:37:35.044911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70de4a28583'
down_revision = 'cf05b2859d56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('AplSer_application_id_fkey', 'AplSer', type_='foreignkey')
    op.drop_constraint('AplSer_service_id_fkey', 'AplSer', type_='foreignkey')
    op.create_foreign_key(None, 'AplSer', 'application', ['application_id'], ['id_application'], ondelete='CASCADE')
    op.create_foreign_key(None, 'AplSer', 'service', ['service_id'], ['id_service'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'AplSer', type_='foreignkey')
    op.drop_constraint(None, 'AplSer', type_='foreignkey')
    op.create_foreign_key('AplSer_service_id_fkey', 'AplSer', 'service', ['service_id'], ['id_service'])
    op.create_foreign_key('AplSer_application_id_fkey', 'AplSer', 'application', ['application_id'], ['id_application'])
    # ### end Alembic commands ###
