"""empty message

Revision ID: d2880cca3c27
Revises: 
Create Date: 2024-04-23 21:52:29.949927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2880cca3c27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_service')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('haswhed_password', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id_application', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('work_start_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('id_executor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_executor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_service'], ['service.id_service'], ),
    sa.PrimaryKeyConstraint('id_application')
    )
    op.create_table('attachment',
    sa.Column('id_attachment', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_blob', sa.LargeBinary(), nullable=True),
    sa.Column('id_application', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_application'], ['application.id_application'], ),
    sa.PrimaryKeyConstraint('id_attachment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    op.drop_table('application')
    op.drop_table('user')
    op.drop_table('service')
    op.drop_table('role')
    # ### end Alembic commands ###
